root_dir: /app/frontend
listening_port: ${WEB_FRONT_PORT}
backend_listening_port: ${WEB_BACKEND_PORT}
fg_log_file: /var/log/yomo-frontend.log
bg_log_file: /var/log/yomo-backend.log
log_mode: debug
client_id: ${CLIENT_ID}
api_key:   ${API_KEY}
cert_dir: /app/etc/certs
